load("//st:defs.bzl", "st_binary", "st_library")

# An st_library and an st_binary that depends on it, colocated.
st_library(
    name = "doubler",
    srcs = ["doubler.st"],
)

st_binary(
    name = "doubler_app",
    program = "doubler_app.st",
    deps = [":doubler"],
)

cc_test(
    name = "doubler_test",
    srcs = ["doubler_test.cc"],
    deps = [
        ":doubler",
        "@googletest//:gtest_main",
    ],
)