load("//st:defs.bzl", "st_binary", "st_library")

st_library(
    name = "mathlib",
    srcs = ["mathlib.st"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "mathlib_test",
    srcs = ["mathlib_test.cc"],
    deps = [
        ":mathlib",
        "@googletest//:gtest_main",
    ],
)

st_binary(
    name = "doubler_app",
    program = "doubler_app.st",
    deps = [":mathlib"],
)

st_binary(
    name = "st_cycle",
    program = "st_cycle.st",
)
