load("@rules_python//python:pip.bzl", "compile_pip_requirements")

# `bazel run //:requirements.update` regenerates
# requirements_lock.txt (with hashes, plus transitive deps like markupsafe)
# from requirements.in; `bazel test //:requirements.test`
# validates it's still up to date.
compile_pip_requirements(
    name = "requirements",
    requirements_in = "requirements.in",
    requirements_txt = "requirements_lock.txt",
)
