load("@rules_plc//st:defs.bzl", "st_library")

st_library(
    name = "counter",
    srcs = ["counter.st"],
)

cc_test(
    name = "counter_test",
    srcs = ["counter_test.cc"],
    deps = [
        ":counter",
        "@googletest//:gtest_main",
    ],
)

st_library(
    name = "totalizer",
    srcs = ["totalizer.st"],
    deps = [":counter"],
)

cc_test(
    name = "totalizer_test",
    srcs = ["totalizer_test.cc"],
    deps = [
        ":totalizer",
        "@googletest//:gtest_main",
    ],
)
