load("@rules_plc_pip_deps//:requirements.bzl", "requirement")
load("@rules_python//python:py_binary.bzl", "py_binary")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

exports_files([
    "private/dependencies.plc.h.jinja",
    "private/library_stubs.c.jinja",
])

# Renders dependencies.plc.h (a Jinja2 template) after running plc
# --generate-headers -- see private/generate_headers.py.
py_binary(
    name = "generate_headers",
    srcs = ["private/generate_headers.py"],
    legacy_create_init = 0,
    main = "private/generate_headers.py",
    visibility = ["//visibility:public"],
    deps = [requirement("jinja2")],
)

# Renders library_stubs.c.jinja (a Jinja2 template) with the {external}
# stubs found via plc's own AST -- see private/generate_weak_stubs.py.
py_binary(
    name = "generate_weak_stubs",
    srcs = ["private/generate_weak_stubs.py"],
    legacy_create_init = 0,
    main = "private/generate_weak_stubs.py",
    visibility = ["//visibility:public"],
    deps = [requirement("jinja2")],
)
